#ifndef TOKENISER_H_
#define TOKENISER_H_

enum class Token {
    FEOF, UNKNOWN, NUMBER, ID, STRINGCONST, LBRACKET, RBRACKET, LPARENT,
    RPARENT, COMMA, SEMICOLON, DOT, ADDOP, MULOP, RELOP, NOT, ASSIGN,
    KEYWORD, COLON, FLOATCONST, CHARCONST
};

#endif
